# Generated by Django 4.2.9 on 2025-07-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0021_expand_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_id", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "init_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("init_email_confirmed", models.BooleanField(default=False)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
