# Generated by Django 4.2.9 on 2025-07-07 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="owner",
        ),
        migrations.AddField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="plan",
            field=models.CharField(default="free", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="slug_subdomain",
            field=models.SlugField(default="default", unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="trial_ends",
            field=models.DateField(blank=True, null=True),
        ),
    ]
