# Generated by Django 4.2.9 on 2025-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_company_owner_company_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="company",
            name="primary_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
