# Generated by Django 4.2.9 on 2025-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_stripe_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="ip",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="method",
            field=models.CharField(default="GET", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="ms",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status",
            field=models.PositiveSmallIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="grace_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
