# Generated by Django 4.2.9 on 2025-07-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0006_stripeevent_remove_auditlog_ip_auditlog_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
