# Generated by Django 4.2.9 on 2025-07-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0009_add_company_contact_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="is_active",
        ),
        migrations.AddField(
            model_name="company",
            name="life_cycle",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("SUSPENDED", "Suspended"),
                    ("DELETED", "Deleted"),
                ],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="CompanySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "key")},
            },
        ),
    ]
