# Generated by Django 4.2.9 on 2025-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0011_add_stripe_webhook_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="company_state_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="company_state_before",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
