# Generated by Django 4.2.9 on 2025-07-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0012_add_auditlog_state_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="db_shard",
            field=models.CharField(default="default", max_length=50),
        ),
    ]
