# Generated by Django 4.2.9 on 2025-07-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_add_company_db_shard"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug_subdomain",
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.UniqueConstraint(
                condition=models.Q(deleted_at__isnull=True),
                fields=("slug_subdomain",),
                name="uniq_active_subdomain",
            ),
        ),
    ]
