# Generated by Django 4.2.9 on 2025-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0014_add_soft_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="row_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(primary_color__regex=r"^#[0-9A-Fa-f]{6}$")
                    | models.Q(primary_color__isnull=True)
                    | models.Q(primary_color="")
                ),
                name="company_color_hex",
            ),
        ),
        migrations.AddConstraint(
            model_name="company",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(billing_email__regex=r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
                    | models.Q(billing_email__isnull=True)
                    | models.Q(billing_email="")
                ),
                name="company_billing_email_valid",
            ),
        ),
    ]
