# Generated by Django 4.2.9 on 2025-07-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0016_enable_rls"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="company",
            name="uniq_active_subdomain",
        ),
        migrations.RemoveField(
            model_name="company",
            name="slug_subdomain",
        ),
    ]
