# Generated by Django 4.2.9 on 2025-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0017_remove_slug_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Payment confirmed via Stripe or manually"
            ),
        ),
    ]
