# Generated by Django 4.2.9 on 2025-07-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("suspended", "Suspended"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
