# Generated by Django 4.2.9 on 2025-07-07 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_remove_company_owner_company_created_by_and_more"),
        ("pages", "0002_product_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="companies.company",
            ),
        ),
    ]
